# Read summary parameters of a fit and display properly here ...

In [4]:
import numpy as np
import pandas as pd
import os

In [5]:
# function to load data and returns pandas frame
def load_data(file_in):
    skipl = 8
    cols = [0,1,2,5,6]
    names = [('par', '|S26'), ('unit','|S20'), 
             ('mle', 'f8'), ('nerr', 'f8'), ('perr', 'f8')
            ]
    d = np.genfromtxt(file_in, skip_header=skipl, usecols=cols, dtype=names)
    df = pd.DataFrame(d)
    return df

In [8]:
file_par = os.path.abspath('/data2/borsato/TRADESsimulations/Kepler-9/EMCEE/2018-11-13_K9_emcee_noRV_001/2018-11-13_run_001/run_full/RV/0668_sim/parameters_summary.txt')
df = load_data(file_par)

In [12]:
df

           par            unit         mle      nerr          perr
0         m2Ms  [M_sun/M_star]    0.000128 -0.000002  1.320271e-06
1           P2          [days]   19.238906 -0.000052  6.321799e-05
2   sqrtecosw2               -    0.246485 -0.002713  2.058269e-03
3   sqrtesinw2               -   -0.013513 -0.001575  2.074458e-03
4      lambda2           [deg]  179.485821 -0.113562  1.493735e-01
5           i2           [deg]   88.981570 -0.005218  7.333879e-03
6         m3Ms  [M_sun/M_star]    0.000088 -0.000001  9.213974e-07
7           P3          [days]   38.985269 -0.000364  3.384290e-04
8   sqrtecosw3               -   -0.252550 -0.000246  2.941680e-04
9   sqrtesinw3               -    0.055918 -0.000513  4.899665e-04
10     lambda3           [deg]  -66.145841 -0.087216  3.197643e-01
11     icoslN3               -  -89.171845 -0.005053  1.492362e-03
12     isinlN3               -    1.680949 -0.487457  1.502218e-01
13          m2       [M_Earth]   43.388095 -1.962787  1.643614e+00
14          e2               -    0.060937 -0.001266  9.745076e-04
15          w2           [deg]  356.861912 -0.390413  5.064878e-01
16         mA2           [deg]    2.623910 -0.587654  5.312664e-01
17          m3       [M_Earth]   29.878459 -1.339498  1.143008e+00
18          e3               -    0.066909 -0.000118  1.006131e-04
19          w3           [deg]  167.515429 -0.122834  1.106090e-01
20          i3           [deg]   89.187687 -0.006173  4.962031e-03
21         lN3           [deg]  178.920064 -0.096444  3.132002e-01
22         mA3           [deg]  -52.581334 -0.113125  1.083025e-01

In [21]:
def display(df):
    
    nrow,ncol = np.shape(df)
    head = '%26s %20s %13s %13s %13s' %('parameter', 'unit', 'mle', '-1\sigma', '+1\sigma')
    print head
    for i in range(0,nrow):
        line = '%26s %20s %13.9f %13.9f %13.9f' %(df.par[i], df.unit[i],
                                                 df.mle[i], df.nerr[i], df.perr[i]
                                                 )
        print line
    return

In [22]:
display(df)

                 parameter                 unit           mle      -1\sigma      +1\sigma
                      m2Ms       [M_sun/M_star]   0.000127576  -0.000001919   0.000001320
                        P2               [days]  19.238905616  -0.000051738   0.000063218
                sqrtecosw2                    -   0.246484602  -0.002712983   0.002058269
                sqrtesinw2                    -  -0.013513471  -0.001574826   0.002074458
                   lambda2                [deg] 179.485821416  -0.113562040   0.149373483
                        i2                [deg]  88.981570414  -0.005218039   0.007333879
                      m3Ms       [M_sun/M_star]   0.000087853  -0.000001293   0.000000921
                        P3               [days]  38.985268766  -0.000363619   0.000338429
                sqrtecosw3                    -  -0.252550457  -0.000245982   0.000294168
                sqrtesinw3                    -   0.055917743  -0.000513370   0.000489966
                   lambda3                [deg] -66.145841345  -0.087215652   0.319764302
                   icoslN3                    - -89.171844521  -0.005053386   0.001492362
                   isinlN3                    -   1.680948629  -0.487456548   0.150221829
                        m2            [M_Earth]  43.388095362  -1.962786929   1.643614101
                        e2                    -   0.060937273  -0.001265742   0.000974508
                        w2                [deg] 356.861911576  -0.390413470   0.506487811
                       mA2                [deg]   2.623909840  -0.587653667   0.531266428
                        m3            [M_Earth]  29.878459171  -1.339498036   1.143007963
                        e3                    -   0.066908527  -0.000117783   0.000100613
                        w3                [deg] 167.515428593  -0.122833533   0.110609025
                        i3                [deg]  89.187686614  -0.006172914   0.004962031
                       lN3                [deg] 178.920064321  -0.096444318   0.313200168
                       mA3                [deg] -52.581334259  -0.113125201   0.108302510

In [25]:
print -66.145841345 % 360.
print -52.581334259 % 360.

293.854158655
307.418665741